#!/bin/sh

set -eu

# Check Docker remote host
if [ -z "$INPUT_REMOTE_HOST" ]; then
    echo "Input remote_host is required!"
    exit 1
fi

# Check remote host SSH private key
if [ -z "$INPUT_SSH_PRIVATE_KEY" ]; then
    echo "Input ssh_private_key is required for SSH hosts!"
    exit 1
fi

USERNAME=${INPUT_REMOTE_USER:-root}

echo "Registering SSH keys..."

mkdir -p "$HOME/.ssh"
printf '%s' "$INPUT_SSH_PRIVATE_KEY" > "$HOME/.ssh/docker"
chmod 600 "$HOME/.ssh/docker"
eval $(ssh-agent)
ssh-add "$HOME/.ssh/docker"

echo "Connecting to $INPUT_REMOTE_HOST..."
ssh-keyscan $INPUT_REMOTE_HOST >> /etc/ssh/ssh_known_hosts

docker context create --docker host=ssh://$USERNAME@$INPUT_REMOTE_HOST swarm

# Login into docker registry
if [[ ! -z "$INPUT_REGISTRY_USERNAME" && ! -z "$INPUT_REGISTRY_PASSWORD" ]]; then
    docker login -u $INPUT_REGISTRY_USERNAME -p $INPUT_REGISTRY_PASSWORD
fi

exec $@
